### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by ritesh**
The example doesn't work, it should be `from flask_prometheus import monitor`

### CODE REVIEW

**Comment by dabcoder** [comment]
👍
Also there is an indentation issue here (in the basic usage section):
```
def hello()
return 'Hello'
```
Should be:
```
def hello():
  return 'Hello'
```
Possible to update in your PR?

**Comment by ritesh** [comment]
Fixed indentation :)

**Comment by dabcoder** [comment]
... Also just realised that the link to the Prometheus website seems broken: https://github.com/sbarratt/flask-prometheus/blob/master/prometheus.io (404 on my side)
Should be:
https://prometheus.io

**Comment by ritesh** [comment]
The link was missing https://, fixed now.

**Pull request merged**
